In [1]:
import numpy as np
import pandas as pd

try:
    from sklearn.cross_validation import train_test_split
except:
    from sklearn.model_selection import train_test_split
    print('Model selection')

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_squared_error

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

Model selection

In [2]:
df = pd.read_csv('titanic.csv')
df = df.drop(['PassengerId','Name','Ticket','Cabin','Survived'],axis = 1)
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Sex'] = df['Sex'].map({'female':0,'male':1})

def dummy_data(data, columns):
    for column in columns:
        data = pd.concat([data, pd.get_dummies(data[column], prefix=column)], axis=1)
        data = data.drop(column, axis=1)
    return data
dummy_columns = ['Pclass','Embarked']
df=dummy_data(df, dummy_columns)

X = df.drop('Fare', axis = 1).values
y = df['Fare'].values

In [3]:
X = df.drop('Fare', axis = 1).values
y = df['Fare'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)
print('Training Data:',X_train.shape[0])
print('Testing Data:',X_test.shape[0])

Training Data: 623
Testing Data: 268

In [8]:
df

,Sex,Age,SibSp,Parch,Fare,Pclass_1,Pclass_2,Pclass_3,Embarked_C,Embarked_Q,Embarked_S
0,1,22.000000,1,0,7.2500,0,0,1,0,0,1
1,0,38.000000,1,0,71.2833,1,0,0,1,0,0
2,0,26.000000,0,0,7.9250,0,0,1,0,0,1
3,0,35.000000,1,0,53.1000,1,0,0,0,0,1
4,1,35.000000,0,0,8.0500,0,0,1,0,0,1
5,1,29.699118,0,0,8.4583,0,0,1,0,1,0
6,1,54.000000,0,0,51.8625,1,0,0,0,0,1
7,1,2.000000,3,1,21.0750,0,0,1,0,0,1
8,0,27.000000,0,2,11.1333,0,0,1,0,0,1
9,0,14.000000,1,0,30.0708,0,1,0,1,0,0
10,0,4.000000,1,1,16.7000,0,0,1,0,0,1
11,0,58.000000,0,0,26.5500,1,0,0,0,0,1
12,1,20.000000,0,0,8.0500,0,0,1,0,0,1
13,1,39.000000,1,5,31.2750,0,0,1,0,0,1
14,0,14.000000,0,0,7.8542,0,0,1,0,0,1
15,0,55.000000,0,0,16.0000,0,1,0,0,0,1
16,1,2.000000,4,1,29.1250,0,0,1,0,1,0
17,1,29.699118,0,0,13.0000,0,1,0,0,0,1
18,0,31.000000,1,0,18.0000,0,0,1,0,0,1
19,0,29.699118,0,0,7.2250,0,0,1,1,0,0
20,1,35.000000,0,0,26.0000,0,1,0,0,0,1
21,1,34.000000,0,0,13.0000,0,1,0,0,0,1
22,0,15.000000,0,0,8.0292,0,0,1,0,1,0
23,1,28.000000,0,0,35.5000,1,0,0,0,0,1
24,0,8.000000,3,1,21.0750,0,0,1,0,0,1
25,0,38.000000,1,5,31.3875,0,0,1,0,0,1
26,1,29.699118,0,0,7.2250,0,0,1,1,0,0
27,1,19.000000,3,2,263.0000,1,0,0,0,0,1
28,0,29.699118,0,0,7.8792,0,0,1,0,1,0
29,1,29.699118,0,0,7.8958,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
861,1,21.000000,1,0,11.5000,0,1,0,0,0,1
862,0,48.000000,0,0,25.9292,1,0,0,0,0,1
863,0,29.699118,8,2,69.5500,0,0,1,0,0,1
864,1,24.000000,0,0,13.0000,0,1,0,0,0,1
865,0,42.000000,0,0,13.0000,0,1,0,0,0,1
866,0,27.000000,1,0,13.8583,0,1,0,1,0,0
867,1,31.000000,0,0,50.4958,1,0,0,0,0,1
868,1,29.699118,0,0,9.5000,0,0,1,0,0,1
869,1,4.000000,1,1,11.1333,0,0,1,0,0,1
870,1,26.000000,0,0,7.8958,0,0,1,0,0,1
871,0,47.000000,1,1,52.5542,1,0,0,0,0,1
872,1,33.000000,0,0,5.0000,1,0,0,0,0,1
873,1,47.000000,0,0,9.0000,0,0,1,0,0,1
874,0,28.000000,1,0,24.0000,0,1,0,1,0,0
875,0,15.000000,0,0,7.2250,0,0,1,1,0,0
876,1,20.000000,0,0,9.8458,0,0,1,0,0,1
877,1,19.000000,0,0,7.8958,0,0,1,0,0,1
878,1,29.699118,0,0,7.8958,0,0,1,0,0,1
879,0,56.000000,0,1,83.1583,1,0,0,1,0,0
880,0,25.000000,0,1,26.0000,0,1,0,0,0,1
881,1,33.000000,0,0,7.8958,0,0,1,0,0,1
882,0,22.000000,0,0,10.5167,0,0,1,0,0,1
883,1,28.000000,0,0,10.5000,0,1,0,0,0,1
884,1,25.000000,0,0,7.0500,0,0,1,0,0,1
885,0,39.000000,0,5,29.1250,0,0,1,0,1,0
886,1,27.000000,0,0,13.0000,0,1,0,0,0,1
887,0,19.000000,0,0,30.0000,1,0,0,0,0,1
888,0,29.699118,1,2,23.4500,0,0,1,0,0,1
889,1,26.000000,0,0,30.0000,1,0,0,1,0,0
890,1,32.000000,0,0,7.7500,0,0,1,0,1,0

In [4]:
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

slr = LinearRegression()
slr.fit(X_train_std, y_train)

y_train_pred = slr.predict(X_train_std)
y_test_pred = slr.predict(X_test_std)

print('(MSE) train: %.2f, test: %.2f'%(mean_squared_error(y_train,y_train_pred), mean_squared_error(y_test,y_test_pred)))
print('(R^2) train: %.2f, test: %.2f'%(r2_score(y_train,y_train_pred), r2_score(y_test,y_test_pred)))

(MSE) train: 1327.93, test: 1576.21
(R^2) train: 0.43, test: 0.44

In [8]:
lin_regr = LinearRegression()
quad_regr = LinearRegression()
cubic_regr = LinearRegression()

quadratic = PolynomialFeatures(degree=2)
cubic = PolynomialFeatures(degree=3)

X_quad_train = quadratic.fit_transform(X_train_std)
X_quad_test = quadratic.fit_transform(X_test_std)
X_cubic_train = cubic.fit_transform(X_train_std)
X_cubic_test = cubic.fit_transform(X_test_std)

lin_regr.fit(X_train_std, y_train)
linear_r2_train = r2_score(y_train, lin_regr.predict(X_train_std))
linear_r2_test = r2_score(y_test, lin_regr.predict(X_test_std))

quad_regr.fit(X_quad_train, y_train)
quad_r2_train = r2_score(y_train, quad_regr.predict(X_quad_train))
quad_r2_test = r2_score(y_test, quad_regr.predict(X_quad_test))

cubic_regr.fit(X_cubic_train,y_train)
cubic_r2_train =  r2_score(y_train, cubic_regr.predict(X_cubic_train))
cubic_r2_test = r2_score(y_test, cubic_regr.predict(X_cubic_test))

print('(R^2) train:\ndegree=1: %.2f, degree=2: %.2f, degree=3: %.2f'%(linear_r2_train, quad_r2_train, cubic_r2_train))
print('(R^2) test:\ndegree=1: %.2f, degree=2: %.2f, degree=3: %.2f'%(linear_r2_test, quad_r2_test, cubic_r2_test))

(R^2) train:
degree=1: 0.43, degree=2: 0.53, degree=3: 0.59
(R^2) test:
degree=1: 0.44, degree=2: 0.53, degree=3: -5921983708786483200.00

In [23]:
ridgeReg = Ridge(alpha=0.01, normalize=True)
ridgeReg.fit(X_cubic_train, y_train)

y_train_pred = ridgeReg.predict(X_cubic_train)
y_test_pred = ridgeReg.predict(X_cubic_test)

print('(MSE) train: %.2f, test: %.2f'%(mean_squared_error(y_train,y_train_pred), mean_squared_error(y_test,y_test_pred)))
print('(R^2) train: %.2f, test: %.2f'%(r2_score(y_train,y_train_pred), r2_score(y_test,y_test_pred)))

(MSE) train: 952.83, test: 1526.89
(R^2) train: 0.59, test: 0.45

In [21]:
lassoReg = Lasso(alpha=0.01, normalize=True)
lassoReg.fit(X_cubic_train, y_train)

y_train_pred = lassoReg.predict(X_cubic_train)
y_test_pred = lassoReg.predict(X_cubic_test)

print('(MSE) train: %.2f, test: %.2f'%(mean_squared_error(y_train,y_train_pred), mean_squared_error(y_test,y_test_pred)))
print('(R^2) train: %.2f, test: %.2f'%(r2_score(y_train,y_train_pred), r2_score(y_test,y_test_pred)))

(MSE) train: 987.19, test: 1380.95
(R^2) train: 0.58, test: 0.51

//anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1295.0631529238308, tolerance: 144.8514584709401
  positive)